openapi: 3.0.0
info:
  title: SawitPro
  description: SawitPro Test Assesment - Renaldi Husin
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  minLength: 10
                  maxLength: 13
                fullName:
                  type: string
                  minLength: 3
                  maxLength: 60
                password:
                  type: string
                  minLength: 6
                  maxLength: 64
      responses:
        '200':
          description: User registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
    servers:
      - url: http://localhost:8080
  /login:
    post:
      summary: Login with phone number and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  token:
                    type: string
        '400':
          description: Invalid phone number or password
    servers:
      - url: http://localhost:8080
  /profile:
    get:
      summary: Get user profile
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  fullName:
                    type: string
                  phone:
                    type: string
        '403':
          description: Unauthorized
    servers:
      - url: http://localhost:8080
    security:
      - BearerAuth: []
  /profile/update:
    put:
      summary: Update user profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: User profile updated successfully
        '403':
          description: Unauthorized
        '409':
          description: Conflict - Phone number already exists
    servers:
      - url: http://localhost:8080
    security:
      - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
